name: audio-analysis
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.21.0
  - pandas>=1.3.0
  - tqdm>=4.65.0
  - pip:
    - torch>=2.0.0
    - torchaudio>=2.0.0
    - librosa>=0.9.0
    - rich>=10.0.0
    - bert-score>=0.3.11
    - jiwer>=2.3.0
    - transformers>=4.30.0
    - soundfile>=0.12.1
    - webrtcvad>=2.0.10
    - indic-nlp-library>=0.92
    - python-Levenshtein>=0.20.0 
